version: "3.9"
networks:
  nodes_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.2.0/16
services:
  node-arthur:
    container_name: node-arthur
    networks:
      nodes_network:
        ipv4_address: 172.24.2.1
    build: .
    environment:
      NODE_ID: arthur
      NODE_HOST: 172.24.2.1
      NODE_PORT: 8000
      NODE_CHANCE: 0.5
      NODE_EVENTS: 20
      NODE_MIN_DELAY: 1500
      NODE_MAX_DELAY: 2000
  node-willian:
    container_name: node-willian
    networks:
      nodes_network:
        ipv4_address: 172.24.2.2
    build: .
    environment:
      NODE_ID: willian
      NODE_HOST: 172.24.2.2
      NODE_PORT: 8000
      NODE_CHANCE: 0.7
      NODE_EVENTS: 25
      NODE_MIN_DELAY: 1500
      NODE_MAX_DELAY: 2000
  node-luiz:
    container_name: node-luiz
    networks:
      nodes_network:
        ipv4_address: 172.24.2.3
    build: .
    environment:
      NODE_ID: luiz
      NODE_HOST: 172.24.2.3
      NODE_PORT: 8000
      NODE_CHANCE: 0.79
      NODE_EVENTS: 30
      NODE_MIN_DELAY: 1500
      NODE_MAX_DELAY: 2000
